version: "3"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3000"
    depends_on:
      - backend
